### ISSUE TITLE
Horizontal alignment

### ISSUE THREAD

**Issue by vuxor** [IvanaaVasic/Card#1]
https://github.com/IvanaaVasic/Card/blob/91fcf4137ae8e8a6e6d0fc7a40fe809cd1977df7/index.html#L24
Name and age are not in horizontal alignment.
Try with span tags instead of div

**Comment by IvanaaVasic** [comment]
> https://github.com/IvanaaVasic/Card/blob/91fcf4137ae8e8a6e6d0fc7a40fe809cd1977df7/index.html#L24
> 
> 
> Name and age are not in horizontal alignment.
> Try with span tags instead of div

Thank you for the comment, I corrected the issue and added "align-items: center;" in the parent div which is "display: flex;" and I also put a span tag for semantic reasons.
